In [3]:
import numpy as np
print('1 D array')
a = np.array([1,2,3])
print(a)

1 D array
[1 2 3]


In [6]:
print('2D Array')
b = np.array([[1,2,3],[4,5,6]])
print(b)

2D Array
[[1 2 3]
 [4 5 6]]


In [ ]:
# tell what type of data
type(a)
type(b) 

numpy.ndarray

In [ ]:
# size in array
print(a.size)
print(b.size)

3
6


In [ ]:
# dtype tell what type of data 
print(a.dtype)
print(b.dtype)

int64


In [10]:
# np.empty((rows,column), dtype=int) 

np.empty((2,3), dtype=int)

array([[         136883,               0,               0],
       [              0, 136525885024968, 136525885024968]])